FROM node:20.6.1 as build

WORKDIR /app

COPY package*.json .

COPY . .

RUN npm install

RUN npm run build

FROM nginx:1.25.3

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
